apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "osrm.fullname" . }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      containers:
        - name: osrm-backend
          image: {{ .Values.osrm.backend.image }}
          imagePullPolicy: IfNotPresent
          command: 
          {{- toYaml .Values.osrm.backend.command | nindent 12 }}
          volumeMounts:
          - mountPath: {{ .Values.osrm.backend.mountPath }}
            name:  {{ .Values.logsVolume.name }}
          ports:
          - containerPort: 5000
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1000
        - name: osrm-frontend
          image: {{ .Values.osrm.frontend.image }}
          imagePullPolicy: IfNotPresent
          env:
          - name: OSRM_BACKEND
            value: http://localhost:5000
          - name: OSRM_CENTER
            value: {{ .Values.osrm.frontend.center }}
          ports:
          - containerPort: 9966
            protocol: TCP 
          readinessProbe:
            tcpSocket:
              port: 9966
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1000
      volumes:
        - name: {{ .Values.logsVolume.name }}
          nfs:
            server: {{ .Values.logsVolume.nfs.server }}
            path: {{ .Values.logsVolume.nfs.path }}