
replicas: 1

nameOverride: ""
fullnameOverride: ""

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0
  
nodeSelector:
  purpose: memory_optimized

osrm:
  frontend:
    name: osrm-frontend
    image: osrm/osrm-frontend
    targetBackend: http://osrm-backend:5000
    center: '42.303329,-83.234070'
    containerPort: 9966
    exposePort: 80

service:
  type: LoadBalancer

labels:
  Group: NavTeam
  Owner: jiezhang2
  Product: OSRM
  TNService: OSRM 
