
replicas: 1

nameOverride: ""
fullnameOverride: ""

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0
  
nodeSelector:
  routing-osrm/role: routing-osrm

osrm:
  frontend:
    name: osrm-frontend
    image: osrm/osrm-frontend
    targetBackend: http://localhost:5000
    center: '42.303329,-83.234070'
    containerPort: 9966
    exposePort: 9966

service:
  type: LoadBalancer