
replicas: 1

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

osrm:
  frontend:
    name: osrm-frontend
    image: osrm/osrm-frontend
    targetBackend: http://osrm-backend:5000
    center: '42.303329,-83.234070'
    containerPort: 9966
    exposePort: 80

service:
  type: LoadBalancer

