apiVersion: v1
kind: Service
metadata:
  name: {{ include "osrm-frontend.fullname" . }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: {{ .Values.osrm.frontend.name }}
    port: {{ .Values.osrm.frontend.exposePort }}
    protocol: TCP
    targetPort: {{ .Values.osrm.frontend.containerPort }}
