apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osrm
  namespace: routing-osrm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: routing
    spec:
      nodeSelector:
        routing-osrm/role: routing-osrm
      containers:
        - name: osrm-backend
          image: TELENAV_OSRM_BACKEND_DOCKER_IMAGE
          imagePullPolicy: IfNotPresent
          args: ["routed_startup"]
          ports:
          - containerPort: 5000
            protocol: TCP 
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1000
