apiVersion: v1
kind: Service
metadata:
  name: routing-osrm-service
  namespace: routing-osrm
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: routing
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
