name: Go CI

on:
  push:
    branches: 
      - '**'
    paths:
    - 'integration/**'

env:
  GO_PROJECT_PATH: integration/

jobs:

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: cd ${GO_PROJECT_PATH} && go build -v ./...
    - name: Test
      run: cd ${GO_PROJECT_PATH} && go test -v ./...

  go-linter:
    name: Go Linter
    runs-on: ubuntu-latest
    steps:
    - name: go1.13 linter
      uses: shoukoo/golang-pipeline/go1.13/linter@master
      with:
        GOLINT: on
        GOLINTPATH: ${{ env.GO_PROJECT_PATH }}
        MISSPELL: off
