name: osrm-backend PR CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - 'master'
      - 'release/**'
    paths:
    - '**.cmake'
    - '**.cc'
    - '**.cpp'
    - '**.h'
    - '**.hpp'

jobs:

  pr-ci-linux:
    name: osrm-backend PR CI (ubuntu)
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: mkdir build && cd build && cmake ../ -DENABLE_MASON=1 && cmake --build . -- -j

  pr-ci-macosx:
    name: osrm-backend PR CI (osx)
    runs-on: macos-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: mkdir build && cd build && cmake ../ -DENABLE_MASON=1 && cmake --build . -- -j

