name: Release cmd/oasis

on: 
  release:
    types: [created]

env:
  CMD_PATH: ./integration/cmd/oasis
  BINARY_NAME: oasis


jobs:
  releases-matrix:
    name: Release cmd/oasis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "${{ env.CMD_PATH }}"
        binary_name: "${{ env.BINARY_NAME }}"
